Repository WiiLink24/room-server, pull requests merged in 2024-06, with the labels that each got.

#71 add ds mov uploading?
  theunderground/forms.py
  theunderground/mobiclip.py
  theunderground/movies.py
Labels: enhancement, help wanted

#77 Add OIDC support
  config-example.py
  models.py
  requirements.txt
  room.py
  templates/includes/sidebar.html
  templates/login.html
  templates/underground.html
  templates/user_new.html
  templates/user_pwchange.html
  theunderground/admin.py
  theunderground/categories.py
  theunderground/concierge.py
  theunderground/forms.py
  theunderground/intro_info.py
  theunderground/miis.py
  theunderground/movies.py
  theunderground/news.py
  theunderground/pay_categories.py
  theunderground/pay_movies.py
  theunderground/pay_posters.py
  theunderground/posters.py
  theunderground/room_data.py
  theunderground/room_types.py
  theunderground/rooms.py
Labels: enhancement

#81 fix: overwrite redirect URI support
  config-example.py
  room.py
Labels: bug
